# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "PyCon Ireland 2017 - Ireland's Python Conference"
email: "pycon@python.ie"
description: "Python Ireland Annual Python Conference"
baseurl: "/pyconie"
url: "https://pythonireland.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-53856571-1"
googleAnalyticsSiteUrl: "python.ie"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Python Ireland"
#organizerAlternateName: "Google Developer Group Lviv"
organizerDescription: "The Python Ireland Committee"
organizerEmail: "pycon@python.ie"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://python.ie/"

# Head
metaKeywords: "event, pycon, python, programming, pydata"
twitterAccount: "@PythonIreland"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://google.ie"
c4sponsorsUrl: "http://python.ie/pycon-2017/call-for-sponsors/"


# Navigation
navigationLinks:
 - {permalink: "/#partners", text: "Sponsors"}
 - {permalink: "/#tickets", text: "Tickets"}
 - {permalink: "/#location-map", text: "Location"}
# - {permalink: "/schedule/", text: "Schedule"}
# - {permalink: "/speakers/", text: "Speakers"}
# - {permalink: "/team/", text: "Team"}
bottomNavigationLinks:
 - {link: "https://google.ie", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "https://google.ie", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "PyConIE 2017 - Ireland's Python Conference"
eventDate: "Sat 21st - Sun 22nd October "
typeoutTextValues: ''
typeoutFallback: ""
heroButtons:
 - {permalink: "/#partners", text: "Become a sponsor"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About PyConIE 2017"
aboutBlock:
 - {title: "Talks", image: "conference.jpg", text: "The best talks form Irish and International speaker about Python and related technologies." }
 - {title: "Workshops", image: "workshop.jpg", text: "Full workshop tracks to up-skill on some new technology." }
 - {title: "Networking", image: "networking.jpg", text: "Meet new friends and enjoy Dublin City, enjoy our entertainment events!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "400", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "32", specialCharacter: "+", info: "hours", detail: "of Python related talks"}
 - {count: "25", specialCharacter: "+", info: "speakers", detail: "from around the world"}
 - {count: "2", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Radisson Blu"
eventLocationLink: "https://www.radissonblu.com/en/royalhotel-dublin"
eventStreetAddress: "Golden Lane"
eventAddressLocality: "Dublin"
#eventAddressLocalityRegion: "Ireland"
# eventPostalCode: "79000"
eventAddressCountry: "Ireland"
eventStartTime: "2014-10-25T10:00"
eventDoorTime: "09:00"
eventEndTime: "2014-10-25T20:00"
eventPlaceCoordinates: "53.3400212, -6.3213563"
mapCenterCoordinates: "53.3400212, -6.3213563"
mapMobileCenterCoordinates: "53.3400212, -6.3213563"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Latest Tweets!"
twitterHashTag: "pyconie"
#twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Sponsors"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
#subscribeImage: "subscribe.jpg"
#subscribeTitle: "Subscribe for updates"
#subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
#subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Tickets"
ticketsInfo: "Tickets grant access to all conference sections, coffee breaks, lunch and entertainment. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Corporate"
  price: "TBD"
  priceCurrency: "EUR"
  ticketsNumber: "300"
  #ribbon: "-20%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  additionalInfo: "Please purchase this ticket if your employer is paying for your ticket."
  buyButtonText: "Coming Soon"
  disabled: true
 -
  name: "Standard Rate"
  price: "TBD"
  priceCurrency: "EUR"
  ticketsNumber: "250"
  #ribbon: "-5%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  additionalInfo: "This is the standard rate"
  buyButtonText: "Coming Soon"
  disabled: true

 -
  name: "Student"
  price: "TBD"
  priceCurrency: "EUR"
  ticketsNumber: "40"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in."
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: false
  soldOutText: "Sold Out"
  disabled: true

 -
  name: "Sunday Only"
  price: "TBD"
  priceCurrency: "EUR"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Coming Soon"
  additionalInfo: "This is a Sunday Only day ticket."
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: false
  soldOutText: "Sold Out"
  disabled: true


# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=pythonireland", icon: "twitter"}
 - {link: "https://facebook.com/pythonireland", icon: "facebook"}
footerBlocks:
 -
  title: "Contacts"
  links:
   - {link: "mailto:pycon@python.ie", text: "pycon@python.ie"}
 -
  title: "FAQ"
  links:
   - {link: "https://python.ie/code-conduct/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

